In [1]:
import pandas as pd

In [2]:
df_laptops = pd.read_csv('laptop_price.csv')

In [3]:
df_laptops.head(3)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00

# duplicated()

## Ejemplo 1

In [4]:
# encontrar duplicados en 1 columna/serie
df_laptops.duplicated('laptop_ID')

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [5]:
# mostrar elementos en dataframe con duplicados en columna 'laptop_ID'
df_laptops[df_laptops.duplicated('laptop_ID')]

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros]
Index: []

In [6]:
# duplicados en 2 o mas columnas
duplicated = df_laptops.duplicated(['Product', 'TypeName', 'Inches'])

In [7]:
# muestra todos los valores duplicados (excepto por el primero - keep='first')
df_laptops[duplicated].sort_values(['Product', 'TypeName'])

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1098,1113,HP,250 G5,Notebook,15.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,1TB HDD,Intel HD Graphics 405,Windows 10,1.96kg,500.0
1170,1188,HP,250 G5,Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.96kg,679.0
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg,928.0
826,835,Asus,ZenBook Flip,2 in 1 Convertible,13.3,Touchscreen / Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1358.0
1275,1293,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0
1289,1307,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0
676,684,Asus,Zenbook 3,Ultrabook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1135.0

## Example 2

Encontrar las laptops mas baratas y caras en cada compañia usando el metodo sort_values() y duplicated() (argumentos: keep "first", "last" and False)

In [8]:
# ordenar dataframe ascendente por "company" y "price"
# mas barato primero y mas caro ultimo
df_laptops = df_laptops.sort_values(['Company', 'Price_euros'])
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.00
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,199.00
1102,1117,Acer,Chromebook 15,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,4GB,16GB SSD,Intel HD Graphics,Chrome OS,2.20kg,209.00
695,703,Acer,TravelMate B117-M,Netbook,11.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.00
1198,1216,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,195,Vero,K147 (N3350/4GB/32GB/FHD/W10),Notebook,14.0,IPS Panel Full HD 1920x1080,Intel Celeron Dual Core N3350 1.1GHz,4GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.3kg,260.00
877,888,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00
192,196,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90
184,188,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00
514,521,Xiaomi,Mi Notebook,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95

In [9]:
# revisar todos las categorias en la columna "Company"
df_laptops.value_counts('Company')

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Vero           4
Xiaomi         4
Google         3
Fujitsu        3
Chuwi          3
LG             3
Huawei         2
dtype: int64

In [10]:
# valores duplicados en la columna "Company" (por defecto -> keep='first')
duplicated_first = df_laptops.duplicated('Company')

In [11]:
# mostrar dataframe con valores duplicados en la columna "Company"
df_laptops[duplicated_first]

# keep='first'(laptops mas baratas por compañia)
# mostrar dataframe con valores no duplicados en la columna "Company"
df_laptops[~duplicated_first]
df_laptops[~duplicated_first][['Company', 'Price_euros']]

# revisar todas las categorias
# df_laptops[~duplicated].value_counts('Company')

        Company  Price_euros
1215       Acer       174.00
1         Apple       898.94
20         Asus       191.90
30        Chuwi       244.99
340        Dell       274.90
983     Fujitsu       649.00
472      Google      1275.00
1268         HP       209.00
170      Huawei      1349.00
909          LG      1899.00
1272     Lenovo       229.00
1169        MSI       839.00
626    Mediacom       239.00
457   Microsoft       989.00
1117      Razer      1029.00
430     Samsung       269.00
159     Toshiba       447.00
1120       Vero       196.00
877      Xiaomi       935.00

In [12]:
# keep='last'
duplicated_last = df_laptops.duplicated('Company', keep='last')
# keep=False
duplicated_false = df_laptops.duplicated('Company', keep=False)

In [13]:
# keep='last'(laptops mas caras por compañia)
# mostrar dataframe con valores no duplicados en columna "Company"
df_laptops[~duplicated_last]
df_laptops[~duplicated_last][['Company', 'Price_euros']]

        Company  Price_euros
1189       Acer      2599.00
17        Apple      2858.00
1066       Asus      3975.00
421       Chuwi       449.00
723        Dell      3659.40
623     Fujitsu       799.00
437      Google      2199.00
749          HP      4389.00
214      Huawei      1499.00
678          LG      2299.00
610      Lenovo      4899.00
177         MSI      2799.00
580    Mediacom       389.00
449   Microsoft      2589.00
196       Razer      6099.00
874     Samsung      1849.00
491     Toshiba      2799.00
191        Vero       260.00
514      Xiaomi      1399.95

In [14]:
# keep=False
# mostrar dataframe con valores no duplicados en columna "Company"
df_laptops[~duplicated_false]

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros]
Index: []

In [15]:
# todos los elementos en la columna "Company" se repiten al menos una vez
df_laptops.value_counts('Company')

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Vero           4
Xiaomi         4
Google         3
Fujitsu        3
Chuwi          3
LG             3
Huawei         2
dtype: int64